[build]
  publish = "public"
  command = "gatsby build"
  [build.environment]
    NODE_VERSION = "12.11.1"
    YARN_VERSION = "1.19.1"
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'
    Content-Security-Policy = "default-src 'none'; object-src 'none'; img-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self'; font-src 'self'; manifest-src 'self';"

