[build]
  publish = "dist"
  command = "nuxt generate --modern"
  [build.environment]
    NODE_VERSION = "12.4.0"
    YARN_VERSION = "1.17.0"
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = 'no-referrer'
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
    Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'
    X-Content-Type-Options = 'nosniff'
    Content-Security-Policy = "default-src 'none'; object-src 'none'; img-src 'self' about: https://p.typekit.net; script-src 'self' https://use.typekit.net  https://cdn.jsdelivr.net 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://use.typekit.net; font-src 'self' use.typekit.net; manifest-src 'self';"
[[headers]]
  for = '/_nuxt/*'
  [headers.values]
    Cache-Control = 'public, max-age=31536000, immutable'
[[headers]]
  for = '/sw.js'
  [headers.values]
    Cache-Control = 'no-cache'
