[build]
  publish = "dist"
  command = "nuxt generate"
[context.production]
  command = "nuxt generate"
  [context.production.environment]
    YARN_FLAGS = "--no-ignore-optional"
    NODE_VERSION = "10.0.0"
    YARN_VERSION = "1.6.0"
