[build]
  publish = "dist"
  command = "nuxt generate"
  NODE_VERSION = "10.13.0"
  YARN_VERSION = "1.12.3"
[context.production]
  command = "nuxt generate"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = 'DENY'
    X-XSS-Protection = '1; mode=block'
    Strict-Transport-Security = 'max-age=31536000; includeSubDomains; preload'
    X-Content-Type-Options = 'nosniff'
    Content-Security-Policy = "default-src 'none'; object-src 'none'; img-src 'self' www.google-analytics.com p.typekit.net; script-src 'self' use.typekit.net www.google-analytics.com; style-src 'self'; font-src 'self' use.typekit.net;"
[[headers]]
  for = '/_nuxt/*'
  [headers.values]
    Cache-Control = 'public, max-age=31536000, immutable'
