name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
    # install dependencies and cache
    - uses: bahmutov/npm-install@v1
    - name: Run ESLint
      run: yarn lint 